### ISSUE TITLE
Roadmap for the next PEtab version

### ISSUE THREAD

**Issue by dilpath** [Benchmarking-Initiative/Benchmark-Models-PEtab#208]
- [ ] rename repo to something like `PEtab-Benchmark-Collection`/`PEtab-Benchmark-Problems` to better match common usage
- [ ] rename `Benchmark-Models` directory to e.g. `Benchmark-Problems` or `Problems`
- [ ] add metadata to each problem in its PEtab YAML file (closes #25)
  - [ ] create schema for such metadata
  - [ ] include objective function value evaluated at nominal parameters (possibly closes #17 unless that it about curation itself). also optionally the Chi2.
  - [ ] include DOI to original publication
  - [ ] copy all relevant metadata from model to PEtab YAML, including e.g. model ID (closes #155)
 - [ ] create script to automatically extract interesting problem "features" then produce a "problem" vs. "feature" matrix TSV file for convenience (closes #18 #19). [example features](https://github.com/LeonardSchmiester/Benchmark-Models/blob/hackathon/hackathon_contributions_new_data_format/model_peculiarities.tsv) (maybe difficult to extract): "splines", "log-scale observables", "parameter-dependent initial conditions". Include all features currently in README overview table.
- [ ] add check for correctly-formatted simulation tables (closes #20)
- [ ] update all PEtab files (e.g. PEtab versions) (closes #1)
- [ ] update contribution guide (closes #32)
- [ ] auto-update CITATION.cff to match Zenodo on new "releases" (closes #164) 
- [ ] consolidate scripts and Python package (#169)
- [ ] require(?) PEtab Results with each problem to ensure "exact"/"easy" reproducibility

**Comment by dweindl** [comment]
> * [ ]  include objective function value evaluated at nominal parameters

That would be super helpful. Also the gradients.
That will make this collection more relevant for regular testing, not just benchmarking.
